# Generated by Django 6.0.4 on 2026-04-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Veterinario que registró o gestiona a este dueño', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_ip',
            field=models.CharField(blank=True, help_text='Dirección IP de aceptación', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_version',
            field=models.CharField(blank=True, help_text='Versión de los Términos aceptados', max_length=20, null=True),
        ),
    ]
