# Generated by Django 6.0.4 on 2026-04-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_managed_by_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(help_text='Texto completo del aviso de privacidad')),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Solo una versión puede estar activa a la vez')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versión de Política de Privacidad',
                'verbose_name_plural': 'Versiones de Política de Privacidad',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_version',
            field=models.ForeignKey(blank=True, help_text='Versión exacta del aviso aceptada por el usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='users.privacypolicyversion'),
        ),
    ]
