# Generated by Django 6.0.4 on 2026-05-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_privacypolicyversion_alter_user_terms_accepted_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicyversion',
            options={'ordering': ['-effective_date'], 'verbose_name': 'Versión de Política de Privacidad', 'verbose_name_plural': 'Privacy Policy Versions'},
        ),
    ]
