"""
Transactional email service.

Design (multi-clinic, Ley 1581):
- The clinic never sets a password. New owners receive a link to set their own.
- Existing owners (added by a 2nd clinic) get a notice and use their current password.
- The secure link is generated by the Firebase Admin SDK; delivery goes through our
  own provider (Brevo) so we control language, branding and which clinic is named.
- Until BREVO_API_KEY / BREVO_SENDER_EMAIL are configured, emails are logged instead
  of sent (so local dev works without a provider). See Fase 4 setup.
"""
import logging
from django.conf import settings

logger = logging.getLogger(__name__)


def _frontend_url():
    return getattr(settings, 'FRONTEND_URL', 'http://localhost:5173')


def _clinic_name(clinic_id):
    from apps.clinics.models import Clinic
    clinic = Clinic.objects.filter(id=clinic_id).first()
    return clinic.name if clinic else 'tu clínica'


def _firebase_password_link(email):
    """Generate a Firebase 'set / reset password' action link, or None on failure."""
    try:
        from firebase_admin import auth as firebase_auth
        return firebase_auth.generate_password_reset_link(email)
    except Exception as exc:
        logger.warning("Could not generate Firebase password link for %s: %s", email, exc)
        return None


def _deliver(to_email, to_name, subject, html_content):
    """
    Send an email via Brevo SMTP using Django's email backend. If SMTP isn't
    configured (no EMAIL_HOST_PASSWORD / sender), log the message (dev fallback).
    """
    sender_email = getattr(settings, 'BREVO_SENDER_EMAIL', '')
    if not getattr(settings, 'EMAIL_HOST_PASSWORD', '') or not sender_email:
        logger.info("[EMAIL:stub] to=%s subject=%r\n%s", to_email, subject, html_content)
        return False

    from django.core.mail import EmailMultiAlternatives
    sender_name = getattr(settings, 'BREVO_SENDER_NAME', 'PostTrack')
    from_email = f"{sender_name} <{sender_email}>"
    try:
        msg = EmailMultiAlternatives(
            subject=subject,
            body='Este correo requiere un cliente que muestre HTML.',
            from_email=from_email,
            to=[to_email],
        )
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return True
    except Exception as exc:
        logger.error("Email send failed to %s: %s", to_email, exc)
        return False


def send_owner_activation_email(user, clinic_id):
    """New account: invite the owner to activate and set their own password."""
    clinic_name = _clinic_name(clinic_id)
    link = _firebase_password_link(user.email) or _frontend_url()
    subject = "Activa tu cuenta en PostTrack"
    html = f"""
        <p>Hola {user.full_name or ''},</p>
        <p><strong>{clinic_name}</strong> te registró en PostTrack para que puedas
        ver tus mascotas, sus seguimientos y enviar reportes.</p>
        <p>Para activar tu cuenta y crear tu contraseña, haz clic aquí:</p>
        <p><a href="{link}">Activar mi cuenta</a></p>
        <p>Si no esperabas este correo, puedes ignorarlo.</p>
        <p>— Equipo PostTrack</p>
    """
    return _deliver(user.email, user.full_name, subject, html)


def send_clinic_added_email(user, clinic_id):
    """Existing account: notify the owner that a clinic added them (uses current password)."""
    clinic_name = _clinic_name(clinic_id)
    link = _frontend_url()
    subject = f"{clinic_name} te agregó en PostTrack"
    html = f"""
        <p>Hola {user.full_name or ''},</p>
        <p><strong>{clinic_name}</strong> te agregó a su lista de propietarios en PostTrack.</p>
        <p>Puedes verla iniciando sesión con tu cuenta de siempre:</p>
        <p><a href="{link}">Ir a PostTrack</a></p>
        <p>— Equipo PostTrack</p>
    """
    return _deliver(user.email, user.full_name, subject, html)
