# Generated by Django 6.0.3 on 2026-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL pública de la imagen (ImgBB)', max_length=500, null=True),
        ),
    ]
