# Generated by Django 6.0.4 on 2026-05-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_add_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción de la regla')),
                ('question_ids', models.JSONField(default=list, help_text='Lista de IDs de preguntas GeneralQuestion que deben estar en SÍ')),
                ('points', models.JSONField(default=dict, help_text='Puntos a sumar por nivel: {"LOW": 0, "MEDIUM": 1, "HIGH": 0}')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Risk Rule',
                'verbose_name_plural': 'Risk Rules',
            },
        ),
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Nivel de riesgo base', max_length=10)),
                ('min_count', models.IntegerField(help_text='Cantidad mínima de respuestas para activar el escalamiento')),
                ('escalates_to', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Nivel al que se escala', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Risk Threshold',
                'verbose_name_plural': 'Risk Thresholds',
                'ordering': ['min_count'],
            },
        ),
    ]
