# Generated by Django 6.0.5 on 2026-05-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_surgicalmonitoring_discharged_at_and_more'),
        ('patients', '0004_add_risk_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Ej: 'Ventana 1 (0-48h)'", max_length=100)),
                ('start_hour', models.IntegerField(help_text='Hora de inicio (inclusive) desde la cirugía.')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ventana de Riesgo',
                'verbose_name_plural': 'Ventanas de Riesgo',
                'ordering': ['start_hour'],
            },
        ),
        migrations.AlterModelOptions(
            name='riskrule',
            options={'verbose_name': 'Combinación de Riesgo', 'verbose_name_plural': 'Combinaciones de Riesgo'},
        ),
        migrations.AlterModelOptions(
            name='riskthreshold',
            options={'ordering': ['min_count'], 'verbose_name': 'Umbral de Riesgo', 'verbose_name_plural': 'Umbrales de Riesgo'},
        ),
        migrations.RemoveField(
            model_name='riskrule',
            name='points',
        ),
        migrations.AddField(
            model_name='riskrule',
            name='result_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='HIGH', help_text='Nivel de riesgo que determina esta combinación', max_length=10),
        ),
        migrations.AlterField(
            model_name='riskrule',
            name='question_ids',
            field=models.JSONField(default=list, help_text='IDs de preguntas GeneralQuestion que deben estar TODAS en SÍ'),
        ),
        migrations.AlterField(
            model_name='riskthreshold',
            name='min_count',
            field=models.IntegerField(help_text='Cantidad mínima de factores para activar el escalamiento'),
        ),
        migrations.CreateModel(
            name='FactorWindowRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, verbose_name='Nivel de riesgo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_risks', to='monitoring.generalquestion', verbose_name='Factor (pregunta)')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_risks', to='patients.riskwindow', verbose_name='Ventana')),
            ],
            options={
                'verbose_name': 'Riesgo por Ventana',
                'verbose_name_plural': 'Riesgos por Ventana',
                'ordering': ['window__start_hour'],
                'unique_together': {('question', 'window')},
            },
        ),
    ]
