# Generated by Django 6.0.4 on 2026-05-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_remove_vetclinic_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetclinic',
            options={'ordering': ['-linked_at'], 'verbose_name': 'Veterinario por Clínica', 'verbose_name_plural': 'Veterinarios por Clínica'},
        ),
        migrations.AlterField(
            model_name='dataauthorization',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Autorización activa'),
        ),
        migrations.AlterField(
            model_name='datapolicy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Política activa'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Vínculo activo'),
        ),
    ]
