# Generated by Django 6.0.3 on 2026-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='instruction_text',
            field=models.TextField(blank=True, help_text='Instrucción sutil para ayudar al dueño a responder.', null=True),
        ),
        migrations.AddField(
            model_name='generalquestion',
            name='instruction_text',
            field=models.TextField(blank=True, help_text='Instrucción sutil para ayudar al dueño a responder.', null=True),
        ),
    ]
