# Generated by Django 6.0.3 on 2026-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_customquestion_instruction_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='processing_status',
            field=models.CharField(choices=[('PROCESSING', 'Processing Images'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='processing_status',
            field=models.CharField(choices=[('PROCESSING', 'Processing Images'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20),
        ),
    ]
