# Generated by Django 6.0.3 on 2026-05-07

from django.db import migrations


def create_default_questions(apps, schema_editor):
    GeneralQuestion = apps.get_model('monitoring', 'GeneralQuestion')

    questions_data = [
        {
            'text': '¿Ha notado hinchazón en la zona de la cirugía?',
            'associated_risk': 'LOW',
            'instruction_text': 'Revise suavemente el área operada sin tocar directamente los puntos.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota se muestra más decaída o con menos energía de lo habitual?',
            'associated_risk': 'LOW',
            'instruction_text': 'Observe si su mascota juega, camina o responde con normalidad.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota NO ha defecado con normalidad desde la cirugía?',
            'associated_risk': 'LOW',
            'instruction_text': 'Es normal que haya cambios menores en las primeras 24-48 horas.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota presenta dificultad o cambios al orinar?',
            'associated_risk': 'LOW',
            'instruction_text': 'Observe el color, frecuencia y esfuerzo al orinar.',
            'is_active': True,
        },
        {
            'text': '¿Ha observado signos de náuseas como arcadas o salivación excesiva?',
            'associated_risk': 'LOW',
            'instruction_text': 'Las arcadas leves pueden ser normales las primeras horas post-cirugía.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota ha vomitado después de la cirugía?',
            'associated_risk': 'LOW',
            'instruction_text': 'Un vómito ocasional puede ser normal; varios episodios requieren atención.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota ha dejado de comer o come menos de lo habitual?',
            'associated_risk': 'LOW',
            'instruction_text': 'Es normal que coma menos el primer día; debe mejorar gradualmente.',
            'is_active': True,
        },
        {
            'text': '¿Ha notado que su mascota bebe más o menos agua de lo normal?',
            'associated_risk': 'LOW',
            'instruction_text': 'Cambios leves son normales; sed excesiva o ausencia total requieren atención.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota interactúa menos de lo habitual?',
            'associated_risk': 'LOW',
            'instruction_text': 'Observe si responde a su nombre, giocattoli o actividades favoritas.',
            'is_active': True,
        },
        {
            'text': '¿La herida presenta secreción, pus o mal olor?',
            'associated_risk': 'MEDIUM',
            'instruction_text': 'Una secreción transparente leve puede ser normal; amarillo/verde NO lo es.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota se muestra apática o sin respuesta a estímulos habituales?',
            'associated_risk': 'MEDIUM',
            'instruction_text': 'Observe si responde a su nombre, caricias o premios.',
            'is_active': True,
        },
        {
            'text': '¿Ha notado que su mascota está caliente al tacto o con signos de fiebre?',
            'associated_risk': 'MEDIUM',
            'instruction_text': 'La temperatura normal en perros/gatos es 38-39.2°C. Use termómetro si es posible.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota lame o muerde constantemente la zona de la cirugía?',
            'associated_risk': 'MEDIUM',
            'instruction_text': 'El lamido constante puede abrir puntos o causar infección.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota muestra dolor al tocar la zona operada?',
            'associated_risk': 'MEDIUM',
            'instruction_text': 'Si se muestra agresiva o躲避 when toca la zona, puede tener dolor.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota ha retirado o dañado los puntos de la herida?',
            'associated_risk': 'HIGH',
            'instruction_text': 'Esto requiere atención veterinaria urgente para evitar infección.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota permanece inmóvil o sin querer moverse durante largos periodos?',
            'associated_risk': 'HIGH',
            'instruction_text': 'La post-cirugía implica descanso, pero no debería ser total ausencia de movimiento.',
            'is_active': True,
        },
        {
            'text': '¿Su mascota presenta dificultad para despertarse o no responde a estímulos?',
            'associated_risk': 'HIGH',
            'instruction_text': 'Esto puede indicar una reacción adversa a la medicación o complicaciones.',
            'is_active': True,
        },
    ]

    for q in questions_data:
        GeneralQuestion.objects.create(**q)


def reverse_questions(apps, schema_editor):
    GeneralQuestion = apps.get_model('monitoring', 'GeneralQuestion')
    GeneralQuestion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_historicalreport_processing_status_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_questions, reverse_questions),
    ]