# Generated by Django 6.0.5 on 2026-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_add_default_surgery_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
