# Generated by Django 6.0.5 on 2026-05-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_historicalreport_reviewed_at_report_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalmonitoring',
            name='discharged_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que se dio de alta (se finalizó el seguimiento).', null=True),
        ),
        migrations.AddField(
            model_name='surgicalmonitoring',
            name='home_release_date',
            field=models.DateTimeField(blank=True, help_text='Salida de la clínica a casa. Inicia el agendamiento de reportes del dueño.', null=True),
        ),
        migrations.AlterField(
            model_name='surgicalmonitoring',
            name='surgery_date',
            field=models.DateTimeField(help_text='Fecha/hora de la cirugía. Define las ventanas de riesgo.'),
        ),
    ]
