# Generated by Django 6.0.5 on 2026-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_surgicalmonitoring_discharged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalquestion',
            name='factor',
            field=models.CharField(blank=True, default='', help_text='Factor clínico asociado (ej: Fiebre, Hinchazón).', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalquestion',
            name='associated_risk',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Riesgo por defecto (respaldo si no hay riesgo por ventana).', max_length=10),
        ),
    ]
