# Generated by Django 6.0.5 on 2026-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_seed_general_question_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalmonitoring',
            name='last_overdue_email_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se envió correo por reporte vencido (anti-spam: 24h entre correos).', null=True),
        ),
        migrations.AddField(
            model_name='surgicalmonitoring',
            name='overdue_emails_sent',
            field=models.IntegerField(default=0, help_text='Cuántos correos de recordatorio se han enviado este ciclo (tope: 3).'),
        ),
    ]
